name: RiseAntiLag
version: 0.1.0
author: jokerthena
main: dev.jokerthena.RiseAntiLag
website: https://github.com/jokerthena
commands:
  qweqweewqqwertyf:
  31182819284159514231:
  zzzzzzzzzzxdkasjxkdjaskdjaskdasaaa:
  enaedkfanekdfajkdfhaekldfhaejkdfhadkfj:
  awksdhaskjdhawkjsdhkjawsdhkjawshdkjawshdkjawhsdkja:
  awsdbaskjdbawkjhsdgbjhasdbvhjawsdbhjawsbdjhawsdawsdawnsjkd:
